



zuul:
  ignoredServices: /**  #忽略框架默认的服务映射路径
#  ignored-patterns: /** #需要代理 ，隐藏的  url映射

  ignoreSecurityHeaders: false #不忽略框架与权限相关的头信息
  addHostHeader: true
  strip-prefix: true  #全局代理  是否需要 加前缀
  prefix: /cloud  # 添加的前缀
  routes:
    client-hi:  #代理名字 随意起
      serviceId: client-hi #  被代理的服务
      path:  /client-hi/**  #拦截的请求

#      strip-prefix: false

server:
  port: 80

  servlet:
    session:
      cookie:
        name: "gate"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: zuul
